root: true
env:
  node: true
  browser: true
parser: babel-eslint
extends:
  - airbnb-base
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
globals:
  console: true
  jQuery: true
  $: true
  window: true
  document: true
  Vue: true
  axios: true,
  HTMLElement: true,
rules:
  quotes:
    - error
    - single
  no-param-reassign:
    - 2
    - props: false
  strict: 0
  semi: 2
  keyword-spacing: 1
settings:
  import/resolver: webpack
